version: '3.1'

services:

  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin1234
    ports:
      - 5432:5432


volumes:
  postgres-data:
    driver: local
